-- ADR-004 Slice B (WhatsApp OTP) — CUSTOM OTP PLANE for Postgres / Supabase pg mode.
--
-- WHY THIS EXISTS
-- The 0002 Postgres port deliberately did NOT recreate auth_users/auth_otps/auth_sessions because it
-- assumed Supabase Auth (AUTH_MODE=supabase) owns identity via the managed `auth.users` schema. But
-- BestOffers also runs a SELF-HOSTED WhatsApp-OTP login (AuthService.requestOtp/verifyOtp →
-- issueSessionForPhone), the SAME flow the Football/MohaFootball project ships (Supabase phone OTP on
-- the Twilio WhatsApp channel). For that custom flow to work against the Supabase Postgres (DB_DRIVER=pg
-- WITHOUT AUTH_MODE=supabase — i.e. our own JWT identity plane, just hosted on Supabase's Postgres), the
-- OTP + session + a user-anchor table must exist in `public`.
--
-- DESIGN: a self-contained `public.auth_users` anchor (NOT Supabase `auth.users`) so the app can mint
-- identities itself (randomUUID) exactly as in SQLite mode. The user-owned tables (profiles /
-- subscriptions / search_quota / notification_tokens) created in 0002 reference `auth.users`; here we
-- re-point those FKs at `public.auth_users` so issueSessionForPhone's inserts succeed under the custom
-- plane. (In AUTH_MODE=supabase the runtime never calls issueSessionForPhone — Supabase verifies the OTP
-- and issues the JWT — so that path is unaffected and still keyed to real auth.users via the trigger.)
--
-- Idempotent. Safe to re-run. Mirrors src/db/migrations/0002_accounts_billing.sql shapes 1:1, ported to
-- Postgres types (TEXT pk → uuid, INTEGER attempts kept int, TEXT iso timestamps → timestamptz).

-- ---------- Identity anchor (custom plane stand-in for Supabase auth.users) ----------
-- Phone PII isolated here (== auth.users.phone in Supabase-Auth mode). NEVER copied into profiles/events.
CREATE TABLE IF NOT EXISTS public.auth_users (
  id            uuid PRIMARY KEY,
  phone_e164    text NOT NULL UNIQUE,             -- +965… PII
  created_at    timestamptz NOT NULL DEFAULT now(),
  last_login_at timestamptz
);

-- ---------- OTP records: hashed code + TTL + attempt lock (F-C1 AC-3/4/6/7/12) ----------
CREATE TABLE IF NOT EXISTS public.auth_otps (
  id          uuid PRIMARY KEY,
  phone_e164  text NOT NULL,
  code_hash   text NOT NULL,                      -- only a hash is persisted (AC-12)
  channel     text NOT NULL DEFAULT 'whatsapp' CHECK (channel IN ('whatsapp','sms')),
  expires_at  timestamptz NOT NULL,               -- now + 5min (AC-4)
  attempts    int NOT NULL DEFAULT 0,             -- ≤5 verify attempts (AC-7)
  consumed_at timestamptz,                        -- set on success; latest code only (AC-5)
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_auth_otps_phone ON public.auth_otps(phone_e164, created_at);

-- ---------- Rotating refresh tokens (device SecureStore under biometric, F-A2) ----------
CREATE TABLE IF NOT EXISTS public.auth_sessions (
  id                 uuid PRIMARY KEY,
  user_id            uuid NOT NULL REFERENCES public.auth_users(id) ON DELETE CASCADE,
  refresh_token_hash text NOT NULL,
  expires_at         timestamptz NOT NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  revoked_at         timestamptz
);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON public.auth_sessions(user_id);

-- ---------- Re-point user-owned FKs from auth.users → public.auth_users for the custom plane ----------
-- 0002 created these FKs against auth.users. Drop-and-recreate against public.auth_users so the custom
-- WhatsApp-OTP flow (which mints its own auth_users rows) can insert profiles/quota/subscriptions.
-- Idempotent: the named constraints are dropped IF EXISTS then re-added against public.auth_users.
-- (FK constraint names below are the Postgres defaults `<table>_<col>_fkey` generated by 0002.)
DO $$
BEGIN
  -- profiles.id
  ALTER TABLE public.profiles            DROP CONSTRAINT IF EXISTS profiles_id_fkey;
  ALTER TABLE public.profiles            ADD  CONSTRAINT profiles_id_fkey
    FOREIGN KEY (id) REFERENCES public.auth_users(id) ON DELETE CASCADE;

  -- notification_tokens.user_id
  ALTER TABLE public.notification_tokens DROP CONSTRAINT IF EXISTS notification_tokens_user_id_fkey;
  ALTER TABLE public.notification_tokens ADD  CONSTRAINT notification_tokens_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE;

  -- subscriptions.user_id
  ALTER TABLE public.subscriptions       DROP CONSTRAINT IF EXISTS subscriptions_user_id_fkey;
  ALTER TABLE public.subscriptions       ADD  CONSTRAINT subscriptions_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE;

  -- search_quota.user_id
  ALTER TABLE public.search_quota        DROP CONSTRAINT IF EXISTS search_quota_user_id_fkey;
  ALTER TABLE public.search_quota        ADD  CONSTRAINT search_quota_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE;
END $$;

-- NOTE: 0002's on_auth_user_created trigger (on Supabase auth.users) still fires in AUTH_MODE=supabase.
-- In the custom plane the app inserts profiles/quota itself inside issueSessionForPhone's tx, so the
-- trigger is simply irrelevant there (no auth.users insert happens). Both modes coexist.
